### ISSUE TITLE
partial rebuilds: filtering packages with regular expressions

### ISSUE THREAD

**Issue by simevo** [Debian/ratt#17]
in some cases there can be a lot of build deps (i.e. doxygen: 700+); after the first ratt run, it is sometimes useful to focus on a few packages; so it would be nice to be able to invoke ratt as in:
```
ratt -recheck -include '^(hwloc|fltk1.3|wcslib|ccfits|qevercloud|libstxxl|caffe|frobby|starpu)$' ../doxygen_1.8.15-1_amd64.changes
```

**Comment by stapelberg** [comment]
Not sure if regexp filtering really is the best choice here, but the feature itself seems reasonable.

You can use `ratt -dry_run` to get the list of packages that will be rebuilt. Maybe we should build on that and make it so that you can split up a ratt invocation into 2 parts: finding affected packages and rebuilding them. That way, you could do a regexp filter (e.g. using `grep`), or just adjust the list in your favorite editor.

What do you think?

**Comment by simevo** [comment]
the command line option fits more my workflow, I'll try a PR with that
