### ISSUE TITLE
use chdist grep-dctrl-sources command instead of dose-ceve

### ISSUE THREAD

**Issue by simevo** [Debian/ratt#21]
for example for doxygen:
```
time chdist grep-dctrl-sources unstable -F Build-Depends-Indep -F Build-Depends -r doxygen -n -s Package | sort | uniq
    735     735    7288

real    0m0,194s
user    0m0,179s
sys     0m0,017s
```

for comparison, dose.ceve finds 738 in 4 minutes (!); whereas for texinfo source:
```
time (chdist grep-dctrl-sources unstable -F Build-Depends-Indep -F Build-Depends -r texinfo -n -s Package && chdist grep-dctrl-sources unstable -F Build-Depends-Indep -F Build-Depends -r info -n -s Package && chdist grep-dctrl-sources unstable -F Build-Depends-Indep -F Build-Depends -r install-info-dbgsym -n -s Package && chdist grep-dctrl-sources unstable -F Build-Depends-Indep -F Build-Depends -r install-info -n -s Package && chdist grep-dctrl-sources unstable -F Build-Depends-Indep -F Build-Depends -r info-dbgsym -n -s Package && chdist grep-dctrl-sources unstable -F Build-Depends-Indep -F Build-Depends -r texinfo-dbgsym -n -s Package) | sort -u | wc
   1582    1582   23026

real    0m0,619s
user    0m0,581s
sys     0m0,045s
```
for this dose-ceve [returns](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=941906#10) 30676 packages (!) in 6 minutes 30 seconds

also see: https://salsa.debian.org/ruby-team/meta/-/blob/master/build-and-upload#L150

**Comment by stapelberg** [comment]
@josch is this okay to do?

**Comment by josch** [comment]
I am confused. dose-ceve and grep-dctrl return completely different results. Depending on what you want you either choose one or the other -- what do you want? Or is it not clear to you what each solution does?

**Comment by zhsj** [comment]
> also see: https://salsa.debian.org/ruby-team/meta/-/blob/master/build-and-upload#L150

I think it's a bug in this script, which ruby team is aware,
https://lists.debian.org/debian-go/2020/03/msg00050.html

**Comment by josch** [comment]
Okay, just let me explain my confusion a bit. My initial confusion was the initial suggestion by @simevo to use grep-dctrl for ratt. I cannot decide for @stapelberg if that's okay or not because ratt is not my software, so I don't get to decide what ratt is supposed to do and what it isn't. But reading that mailing list post and the fact that the function in `build-and-upload` where grep-dctrl is used is called `get_reverse_build_dependencies` makes me afraid that people think that this script is able to find direct reverse build dependencies in Debian. It isn't. The snippet that @simevo posted works on deb822 based Linux distributions with the following limitations:

 - there are no packages with `+` or `.` in their name
 - there exist no virtual packages
 - there are no OR relationships `foo | bar`
 - there are no build conflicts and no dependency conflicts
 - the field `Build-Depends-Arch` doesn't exist
 - there is no multiarch
 - there are no versioned `Provides`
 - there are no `:native` or `:any` annotations
 - there are no architecture annotations
 - there are no architecture restrictions
 - there are no version restrictions
 - there are no build profiles
 - there are no `Essential: yes` packages
 - the build-essential package doesn't exist

If you are okay with that (I cannot tell you that) then using grep-dctrl might be an option for you. Though I would still fix the `-r` argument in it. As it stands, the initial grep-dctrl call will also find `foobar` when it is supposed to find `foo`. There is even the `--whole-pkg` option in grep-dctrl which will do the right thing for binary package relationships (it doesn't support `Build-Depends`) -- but because we already accepted all the limitations from above, it could also be used on source package build dependency fields which now look like normal `Depends` fields.

I apologize if I'm just assuming wrongly here and the snippet is not supposed to find reverse build dependencies in Debian in which case it might do it's job perfectly well. But that mailing list post really makes me afraid that people think it's doing that job. It really is not -- please don't go around suggesting that that is what it's doing. If you don't understand any of the limitations I listed above, please ask and I will explain in more detail. Remember that solving dependency relationships (even if you limit yourself to direct dependencies only!) is a problem that is NP-hard. You can solve sudoku puzzles with a dependency resolver. You cannot hope to replace the thousands of lines of code in dose-ceve or apt with a one-line regex (which is what the grep-dctrl call boils down to). In my opinion the function `get_reverse_build_dependencies` is really badly named and the authors should at least list above limitations as a code comment to prevent anybody from copying the code and using it for their own project in the hope that what does is to get reverse build dependencies in Debian.

**Comment by stapelberg** [comment]
Thank you very much @josch, that sort of explanation is exactly what I was looking for.

@simevo, I’m going to close this as we do want the precision that dose-ceve gives us. ratt isn’t useful if it tells you everything is okay, and then your upload breaks the archive anyway. If you meant your issue differently, please clarify.
